repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        language: system
        entry: gofmt -l -s
        files: \.go$
        pass_filenames: true

      - id: go-vet
        name: go vet
        language: system
        entry: go vet ./...
        files: \.go$
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint
        language: system
        entry: golangci-lint run --new-from-rev=HEAD
        files: \.go$
        pass_filenames: false
